apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-observability
  labels:
    app.kubernetes.io/part-of: knative-operator
    operator.knative.dev/release: v1.9.4
  {{- include "chart.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configObservability.Example | quote }}