apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-knative-serving-operator-aggregated-stable
  labels:
    app.kubernetes.io/part-of: knative-operator
    operator.knative.dev/release: v1.9.4
  {{- include "chart.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - knative-serving
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-knative-serving-operator-aggregated-stable
  labels:
    app.kubernetes.io/part-of: knative-operator
    operator.knative.dev/release: v1.9.4
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-knative-serving-operator-aggregated-stable'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-knative-operator'
  namespace: '{{ .Release.Namespace }}'